import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _lang = 'en';
  String get lang => _lang;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _lang = prefs.getString('app_language') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    _lang = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', code);
    notifyListeners();
  }

  String t(String key) => _translations[_lang]?[key] ?? _translations['en']?[key] ?? key;

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'home': 'Home', 'scan': 'Scan', 'chef_ai': 'CHEF AI', 'saved': 'Saved', 'profile': 'Profile',
      'good_morning': 'Good morning', 'good_afternoon': 'Good afternoon', 'good_evening': 'Good evening',
      'what_cook': 'What shall we cook?', 'quick_actions': 'Quick Actions',
      'scan_ingredients': 'Scan Ingredients', 'ai_recipe_magic': 'AI Recipe Magic',
      'chat_chef': 'Chat with CHEF AI', 'ask_anything': 'Ask anything',
      'meal_planner': 'Meal Planner', 'seven_day': '7-day plan',
      'shopping_list': 'Shopping List', 'auto_generated': 'Auto-generated',
      'saved_recipes': 'Saved Recipes', 'see_all': 'See all',
      'analyze': 'Analyze ingredients', 'find_recipes': 'Find Recipes',
      'choose_cuisine': 'Choose a cuisine 🌍', 'detected': 'Detected ingredients',
      'start_cooking': 'Start Cooking', 'finish_cooking': 'Finish Cooking',
      'next_step': 'Next Step', 'bon_appetit': 'Bon Appétit!',
      'save_recipe': 'Save Recipe', 'cook_again': 'Cook Again',
      'language': 'Language', 'appearance': 'Appearance',
      'notifications': 'Notifications', 'dietary': 'Dietary restrictions',
      'share': 'Share AI Chef', 'rate': 'Rate the app',
      'privacy': 'Privacy Policy', 'terms': 'Terms of Service',
      'logout': 'Log out', 'food_prefs': 'Food Preferences',
      'recipes_scanned': 'Recipes scanned', 'day_streak': 'Day streak',
      'light_mode': 'Light Mode', 'dark_mode': 'Dark Mode',
      'cancel': 'Cancel', 'save': 'Save', 'edit_name': 'Edit name', 'choose_avatar': 'Choose avatar',
      'your_name': 'Your name', 'name_updated': 'Name updated', 'log_out_confirm': 'Are you sure you want to log out?',
      'language_changed': 'Language changed! Restart may be needed.',
      'back_home': 'Back to home', 'rate_recipe': 'Rate this recipe', 'no_saved_yet': 'No saved recipes yet',
      'meal_ready_subtitle': 'Your meal is ready! Enjoy your delicious %s!',
      'saved_recipe_toast': 'Recipe saved to favorites!', 'search_placeholder': 'Search recipes or ask CHEF AI...',
      'log_out': 'Log out', 'new_scan': 'New scan', 'take_photo': 'Take Photo', 'choose_gallery': 'Choose from Gallery',
      'point_camera': 'Point camera at ingredients', 'ai_detect_subtitle': 'AI will detect ingredients and suggest recipes',
      'retake': 'Retake', 'gallery': 'Gallery', 'retry': 'Retry', 'detecting_ingredients': 'Detecting ingredients...',
      'finding_recipes': 'Finding recipes from different cuisines', 'recipes_for_ingredients': 'Recipes for your ingredients',
      'suggest_recipes': 'We\'ll suggest 3–4 recipes using your ingredients', 'saved_exclamation': 'Saved!',
      'recipes_count': 'recipes', 'ingredients_for_recipe': 'Ingredients for this recipe',
      'ask_chef_placeholder': 'Ask CHEF AI anything...', 'chat_welcome': 'Hi! I\'m CHEF AI 👨‍🍳\n\nI\'m your personal cooking assistant! I can help you with:\n• Recipe suggestions\n• Cooking techniques\n• Ingredient substitutions\n• Meal planning\n\nWhat shall we cook today? 🍳',
      'similar_recipes': 'Similar Recipes', 'servings': 'Servings', 'min_total': 'min total', 'min_prep': 'min prep', 'min_cook': 'min cook', 'level': 'level', 'nutrition_per_serving': 'Nutrition per serving',
      'plan_settings': 'Plan Settings', 'diet_type': 'Diet Type', 'daily_calories': 'Daily Calories', 'no_meal_plan_yet': 'No meal plan yet', 'your_week': 'Your Week', 'generate_meal_plan': 'Generate 7-Day Meal Plan',
      'breakfast': 'Breakfast', 'lunch': 'Lunch', 'dinner': 'Dinner', 'step': 'Step', 'of': 'of',
      'quick_meals': 'Quick meals', 'healthy': 'Healthy', 'budget_friendly': 'Budget-friendly', 'italian': 'Italian', 'asian': 'Asian', 'vegetarian': 'Vegetarian',
      'removed_from_favorites': 'Removed', 'undo': 'Undo', 'scan_or_chat': 'Scan ingredients or chat with CHEF AI to find recipes.',
      'monday': 'Monday', 'tuesday': 'Tuesday', 'wednesday': 'Wednesday', 'thursday': 'Thursday', 'friday': 'Friday', 'saturday': 'Saturday', 'sunday': 'Sunday',
      'kcal': 'kcal', 'start_timer': 'Start timer', 'generating_meal_plan': 'CHEF AI is planning your week...', 'generate_meal_plan_hint': 'Generate a personalized 7-day meal plan with CHEF AI', 'chat_error_response': 'Sorry, could not get a response.', 'timer_done': 'Timer done!', 'meal_plan_generated': 'Meal plan generated!', 'loading': 'Loading...',
      'notifications_subtitle': 'Daily cooking reminders', 'notifications_description': 'When enabled, you\'ll receive one daily reminder to open AI Chef and get recipe ideas.', 'share_subtitle': 'Tell your friends', 'rate_subtitle': 'Support us with a review', 'dietary_subtitle': 'Set your preferences',
      'about_app': 'About App', 'about_title': 'AI Chef', 'about_description': 'AI Chef is your smart cooking assistant. Scan ingredients, get recipes from different cuisines, chat with CHEF AI, plan meals and create shopping lists. Cook with confidence! 👨‍🍳',
      'privacy_content': 'We respect your privacy. Your data is stored securely. We do not sell your personal information. Recipe and usage data is used only to improve your experience.',
      'terms_content': 'By using AI Chef you agree to use the app for personal, non-commercial purposes. Recipe content is for inspiration. Always follow food safety guidelines when cooking.',
      'feedback_saved_thanks': 'Saved, thank you for your feedback!',
      'review_title': 'Rate the App', 'review_question': 'How was your experience?', 'review_subtitle': 'Your feedback helps us improve Ai Chef', 'your_rating': 'YOUR RATING', 'your_review': 'YOUR REVIEW', 'review_placeholder': 'Share your thoughts about Ai Chef...', 'submit_review': 'Submit Review', 'select_rating': 'Please select a rating.',
    },
    'ru': {
      'home': 'Главная', 'scan': 'Сканер', 'chef_ai': 'ШЕФ ИИ', 'saved': 'Сохранено', 'profile': 'Профиль',
      'good_morning': 'Доброе утро', 'good_afternoon': 'Добрый день', 'good_evening': 'Добрый вечер',
      'what_cook': 'Что приготовим?', 'quick_actions': 'Быстрые действия',
      'scan_ingredients': 'Сканировать', 'ai_recipe_magic': 'ИИ магия рецептов',
      'chat_chef': 'Чат с ШЕФ ИИ', 'ask_anything': 'Спроси что угодно',
      'meal_planner': 'План питания', 'seven_day': '7-дневный план',
      'shopping_list': 'Список покупок', 'auto_generated': 'Авто-генерация',
      'saved_recipes': 'Сохранённые рецепты', 'see_all': 'Все',
      'analyze': 'Анализировать', 'find_recipes': 'Найти рецепты',
      'choose_cuisine': 'Выбери кухню 🌍', 'detected': 'Обнаруженные продукты',
      'start_cooking': 'Начать готовить', 'finish_cooking': 'Завершить',
      'next_step': 'Следующий шаг', 'bon_appetit': 'Приятного аппетита!',
      'save_recipe': 'Сохранить', 'cook_again': 'Готовить снова',
      'language': 'Язык', 'appearance': 'Внешний вид',
      'notifications': 'Уведомления', 'dietary': 'Диетические ограничения',
      'share': 'Поделиться', 'rate': 'Оценить приложение',
      'privacy': 'Политика конфиденциальности', 'terms': 'Условия использования',
      'logout': 'Выйти', 'food_prefs': 'Пищевые предпочтения',
      'recipes_scanned': 'Рецептов', 'day_streak': 'Дней подряд',
      'light_mode': 'Светлая тема', 'dark_mode': 'Тёмная тема',
      'cancel': 'Отмена', 'save': 'Сохранить', 'edit_name': 'Изменить имя', 'choose_avatar': 'Выберите аватар',
      'your_name': 'Ваше имя', 'name_updated': 'Имя обновлено', 'log_out_confirm': 'Выйти из аккаунта?',
      'language_changed': 'Язык изменён! Может потребоваться перезапуск.',
      'back_home': 'На главную', 'rate_recipe': 'Оцените рецепт', 'no_saved_yet': 'Нет сохранённых рецептов',
      'meal_ready_subtitle': 'Ваше блюдо готово! Приятного аппетита: %s!',
      'saved_recipe_toast': 'Рецепт сохранён!', 'search_placeholder': 'Поиск рецептов или спросите ШЕФ ИИ...',
      'log_out': 'Выйти',
      'new_scan': 'Новый скан', 'take_photo': 'Сделать фото', 'choose_gallery': 'Выбрать из галереи',
      'point_camera': 'Наведите камеру на продукты', 'ai_detect_subtitle': 'ИИ определит продукты и предложит рецепты',
      'retake': 'Переснять', 'gallery': 'Галерея', 'retry': 'Повторить', 'detecting_ingredients': 'Определение продуктов...',
      'finding_recipes': 'Поиск рецептов из разных кухонь', 'recipes_for_ingredients': 'Рецепты по вашим продуктам',
      'suggest_recipes': 'Подберём 3–4 рецепта по вашим продуктам', 'saved_exclamation': 'Сохранено!',
      'recipes_count': 'рецептов', 'ingredients_for_recipe': 'Ингредиенты для этого рецепта',
      'ask_chef_placeholder': 'Спросите CHEF AI что угодно...', 'chat_welcome': 'Привет! Я CHEF AI 👨‍🍳\n\nВаш помощник по готовке! Могу помочь с:\n• Подбором рецептов\n• Техниками готовки\n• Заменами ингредиентов\n• Планированием меню\n\nЧто приготовим сегодня? 🍳',
      'similar_recipes': 'Похожие рецепты', 'servings': 'Порции', 'min_total': 'мин всего', 'min_prep': 'мин подготовка', 'min_cook': 'мин готовка', 'level': 'уровень', 'nutrition_per_serving': 'Пищевая ценность на порцию',
      'plan_settings': 'Настройки плана', 'diet_type': 'Тип питания', 'daily_calories': 'Калории в день', 'no_meal_plan_yet': 'Плана пока нет', 'your_week': 'Ваша неделя', 'generate_meal_plan': 'Создать план на 7 дней',
      'breakfast': 'Завтрак', 'lunch': 'Обед', 'dinner': 'Ужин', 'step': 'Шаг', 'of': 'из',
      'quick_meals': 'Быстрые блюда', 'healthy': 'Здоровое', 'budget_friendly': 'Бюджетно', 'italian': 'Итальянская', 'asian': 'Азиатская', 'vegetarian': 'Вегетарианское',
      'removed_from_favorites': 'Удалено', 'undo': 'Отмена', 'scan_or_chat': 'Отсканируйте продукты или спросите CHEF AI.',
      'monday': 'Понедельник', 'tuesday': 'Вторник', 'wednesday': 'Среда', 'thursday': 'Четверг', 'friday': 'Пятница', 'saturday': 'Суббота', 'sunday': 'Воскресенье',
      'kcal': 'ккал', 'start_timer': 'Запустить таймер', 'generating_meal_plan': 'CHEF AI планирует вашу неделю...', 'generate_meal_plan_hint': 'Создайте персональный план на 7 дней с CHEF AI', 'chat_error_response': 'Не удалось получить ответ.', 'timer_done': 'Таймер завершён!', 'meal_plan_generated': 'План меню создан!', 'loading': 'Загрузка...',
      'notifications_subtitle': 'Ежедневные напоминания о готовке', 'notifications_description': 'Включив, вы будете получать одно напоминание в день открыть AI Chef и получить идеи рецептов.', 'share_subtitle': 'Расскажите друзьям', 'rate_subtitle': 'Поддержите нас отзывом', 'dietary_subtitle': 'Настройте предпочтения',
      'about_app': 'О приложении', 'about_title': 'AI Chef', 'about_description': 'AI Chef — ваш умный помощник по готовке. Сканируйте продукты, получайте рецепты из разных кухонь, общайтесь с CHEF AI, планируйте меню и списки покупок. Готовьте с уверенностью! 👨‍🍳',
      'privacy_content': 'Мы уважаем вашу конфиденциальность. Данные хранятся безопасно. Мы не продаём персональную информацию. Данные рецептов используются только для улучшения сервиса.',
      'terms_content': 'Используя AI Chef, вы соглашаетесь применять приложение в личных целях. Рецепты носят рекомендательный характер. Соблюдайте правила безопасности при готовке.',
      'feedback_saved_thanks': 'Сохранено, спасибо за ваш отзыв!',
      'review_title': 'Оценить приложение', 'review_question': 'Как вам приложение?', 'review_subtitle': 'Ваш отзыв помогает нам улучшать Ai Chef', 'your_rating': 'ВАША ОЦЕНКА', 'your_review': 'ВАШ ОТЗЫВ', 'review_placeholder': 'Поделитесь мнением об Ai Chef...', 'submit_review': 'Отправить отзыв', 'select_rating': 'Выберите оценку.',
    },
    'uz': {
      'home': 'Bosh sahifa', 'scan': 'Skaner', 'chef_ai': 'CHEF AI', 'saved': 'Saqlangan', 'profile': 'Profil',
      'good_morning': 'Xayrli tong', 'good_afternoon': 'Xayrli kun', 'good_evening': 'Xayrli kech',
      'what_cook': 'Nima pishiramiz?', 'quick_actions': 'Tezkor amallar',
      'scan_ingredients': 'Mahsulotlarni skan', 'ai_recipe_magic': 'AI retsept sehri',
      'chat_chef': 'CHEF AI bilan suhbat', 'ask_anything': 'Istalganini so\'rang',
      'meal_planner': 'Ovqat rejasi', 'seven_day': '7 kunlik reja',
      'shopping_list': 'Xarid ro\'yxati', 'auto_generated': 'Avtomatik',
      'saved_recipes': 'Saqlangan retseptlar', 'see_all': 'Hammasi',
      'analyze': 'Tahlil qilish', 'find_recipes': 'Retsept topish',
      'choose_cuisine': 'Oshxona tanlang 🌍', 'detected': 'Aniqlangan mahsulotlar',
      'start_cooking': 'Pishirishni boshlash', 'finish_cooking': 'Tugatish',
      'next_step': 'Keyingi qadam', 'bon_appetit': 'Yaxshi ishtaha!',
      'save_recipe': 'Saqlash', 'cook_again': 'Yana pishirish',
      'language': 'Til', 'appearance': 'Ko\'rinish',
      'notifications': 'Bildirishnomalar', 'dietary': 'Parhez cheklovlari',
      'share': 'Ulashish', 'rate': 'Ilovani baholash',
      'privacy': 'Maxfiylik siyosati', 'terms': 'Foydalanish shartlari',
      'logout': 'Chiqish', 'food_prefs': 'Ovqat afzalliklari',
      'recipes_scanned': 'Retseptlar', 'day_streak': 'Kunlar ketma-ket',
      'light_mode': 'Yorqin rejim', 'dark_mode': 'Qorong\'u rejim',
      'cancel': 'Bekor qilish', 'save': 'Saqlash', 'edit_name': 'Ismni tahrirlash', 'choose_avatar': 'Avatar tanlang',
      'your_name': 'Ismingiz', 'name_updated': 'Ism yangilandi', 'log_out_confirm': 'Chiqishni xohlaysizmi?',
      'language_changed': 'Til o\'zgartirildi! Qayta ishga tushirish kerak bo\'lishi mumkin.',
      'back_home': 'Bosh sahifaga', 'rate_recipe': 'Retseptni baholang', 'no_saved_yet': 'Saqlangan retseptlar yo\'q',
      'meal_ready_subtitle': 'Taomingiz tayyor! Mazza qiling: %s!',
      'saved_recipe_toast': 'Retsept saqlandi!', 'search_placeholder': 'Retsept qidiring yoki CHEF AI dan so\'rang...',
      'log_out': 'Chiqish',
      'new_scan': 'Yangi skan', 'take_photo': 'Rasm olish', 'choose_gallery': 'Galeriyadan tanlash',
      'point_camera': 'Kamerani mahsulotlarga qiling', 'ai_detect_subtitle': 'AI mahsulotlarni aniqlaydi va retseptlar taklif qiladi',
      'retake': 'Qayta olish', 'gallery': 'Galereya', 'retry': 'Qayta urinish', 'detecting_ingredients': 'Mahsulotlar aniqlanmoqda...',
      'finding_recipes': 'Turli oshxonalardan retseptlar', 'recipes_for_ingredients': 'Mahsulotlaringiz bo\'yicha retseptlar',
      'suggest_recipes': '3–4 ta retsept taklif qilamiz', 'saved_exclamation': 'Saqlandi!',
      'recipes_count': 'ta retsept', 'ingredients_for_recipe': 'Ushbu retsept uchun mahsulotlar',
      'ask_chef_placeholder': 'CHEF AI dan istalgan narsani so\'rang...', 'chat_welcome': 'Salom! Men CHEF AI 👨‍🍳\n\nShaxsiy oshpaz yordamchingiz! Yordam bera olaman:\n• Retseptlar taklifi\n• Pishirish usullari\n• Mahsulot almashtirish\n• Ovqat rejalash\n\nBugun nima pishiramiz? 🍳',
      'similar_recipes': 'O\'xshash retseptlar', 'servings': 'Porsiya', 'min_total': 'min jami', 'min_prep': 'min tayyorgarlik', 'min_cook': 'min pishirish', 'level': 'daraja', 'nutrition_per_serving': 'Har bir porsiya uchun qimmat',
      'plan_settings': 'Reja sozlamalari', 'diet_type': 'Dieta turi', 'daily_calories': 'Kunlik kaloriya', 'no_meal_plan_yet': 'Hali reja yo\'q', 'your_week': 'Sizning haftangiz', 'generate_meal_plan': '7 kunlik ovqat rejasini yaratish',
      'breakfast': 'Nonushta', 'lunch': 'Tushlik', 'dinner': 'Kechki ovqat', 'step': 'Qadam', 'of': '/',
      'quick_meals': 'Tez ovqatlar', 'healthy': 'Sog\'lom', 'budget_friendly': 'Arzon', 'italian': 'Italyan', 'asian': 'Osiyo', 'vegetarian': 'Vegetarian',
      'removed_from_favorites': 'Olib tashlandi', 'undo': 'Bekor qilish', 'scan_or_chat': 'Mahsulotlarni skanerlang yoki CHEF AI dan so\'rang.',
      'monday': 'Dushanba', 'tuesday': 'Seshanba', 'wednesday': 'Chorshanba', 'thursday': 'Payshanba', 'friday': 'Juma', 'saturday': 'Shanba', 'sunday': 'Yakshanba',
      'kcal': 'kkal', 'start_timer': 'Taymerni boshlash', 'generating_meal_plan': 'CHEF AI haftangizni rejalashtirmoqda...', 'generate_meal_plan_hint': 'CHEF AI bilan shaxsiy 7 kunlik ovqat rejasini yarating', 'chat_error_response': 'Javob olish mumkin emas.', 'timer_done': 'Taymer tugadi!', 'meal_plan_generated': 'Ovqat rejasi yaratildi!', 'loading': 'Yuklanmoqda...',
      'notifications_subtitle': 'Kunlik pishirish eslatmalari', 'notifications_description': 'Yoqilganda, kuniga bir marta AI Chef ni ochish va retseptlar olish eslatmasi keladi.', 'share_subtitle': 'Do\'stlaringizga ayting', 'rate_subtitle': 'Sharh bilan qo\'llab-quvvatlang', 'dietary_subtitle': 'Afzalliklaringizni o\'rnating',
      'about_app': 'Ilova haqida', 'about_title': 'AI Chef', 'about_description': 'AI Chef — aqlli pishirish yordamchingiz. Mahsulotlarni skanerlang, turli oshxonalardan retseptlar oling, CHEF AI bilan suhbatlashing, ovqat rejasi va xarid ro\'yxatini yarating. Ishonch bilan pishiring! 👨‍🍳',
      'privacy_content': 'Maxfiyligingizni hurmat qilamiz. Ma\'lumotlaringiz xavfsiz saqlanadi. Shaxsiy ma\'lumotlaringizni sotmaymiz. Retsept ma\'lumotlari faqat xizmatni yaxshilash uchun ishlatiladi.',
      'terms_content': 'AI Chef dan foydalanib, siz ilovani shaxsiy maqsadlarda ishlatishga rozisiz. Retseptlar tavsiya xarakteriga ega. Pishirishda xavfsizlik qoidalariga amal qiling.',
      'feedback_saved_thanks': 'Saqlandi, sharhingiz uchun rahmat!',
      'review_title': 'Ilovani baholash', 'review_question': 'Tajribangiz qanday edi?', 'review_subtitle': 'Sharhingiz Ai Chef ni yaxshilashga yordam beradi', 'your_rating': 'BAHOLANGIZ', 'your_review': 'SHARHINGIZ', 'review_placeholder': 'Ai Chef haqida fikringizni yozing...', 'submit_review': 'Sharh yuborish', 'select_rating': 'Baholashni tanlang.',
    },
    'es': {
      'home': 'Inicio', 'scan': 'Escanear', 'chef_ai': 'CHEF IA', 'saved': 'Guardado', 'profile': 'Perfil',
      'good_morning': 'Buenos días', 'good_afternoon': 'Buenas tardes', 'good_evening': 'Buenas noches',
      'what_cook': '¿Qué cocinamos?', 'quick_actions': 'Acciones rápidas',
      'scan_ingredients': 'Escanear ingredientes', 'ai_recipe_magic': 'Magia de recetas IA',
      'chat_chef': 'Chat con CHEF IA', 'ask_anything': 'Pregunta lo que quieras',
      'meal_planner': 'Planificador', 'seven_day': 'Plan de 7 días',
      'shopping_list': 'Lista de compras', 'auto_generated': 'Auto-generado',
      'saved_recipes': 'Recetas guardadas', 'see_all': 'Ver todo',
      'analyze': 'Analizar ingredientes', 'find_recipes': 'Buscar recetas',
      'choose_cuisine': 'Elige cocina 🌍', 'detected': 'Ingredientes detectados',
      'start_cooking': 'Empezar a cocinar', 'finish_cooking': 'Terminar',
      'next_step': 'Siguiente paso', 'bon_appetit': '¡Buen provecho!',
      'save_recipe': 'Guardar', 'cook_again': 'Cocinar de nuevo',
      'language': 'Idioma', 'appearance': 'Apariencia',
      'notifications': 'Notificaciones', 'dietary': 'Restricciones dietéticas',
      'share': 'Compartir', 'rate': 'Valorar la app',
      'privacy': 'Política de privacidad', 'terms': 'Términos de servicio',
      'logout': 'Cerrar sesión', 'food_prefs': 'Preferencias alimentarias',
      'recipes_scanned': 'Recetas escaneadas', 'day_streak': 'Días seguidos',
      'light_mode': 'Modo claro', 'dark_mode': 'Modo oscuro',
      'cancel': 'Cancelar', 'save': 'Guardar', 'edit_name': 'Editar nombre', 'choose_avatar': 'Elegir avatar',
      'your_name': 'Tu nombre', 'name_updated': 'Nombre actualizado', 'log_out_confirm': '¿Cerrar sesión?',
      'language_changed': '¡Idioma cambiado! Puede que necesites reiniciar.',
      'back_home': 'Volver al inicio', 'rate_recipe': 'Valora esta receta', 'no_saved_yet': 'Sin recetas guardadas',
      'meal_ready_subtitle': '¡Tu plato está listo! Disfruta tu delicioso %s!',
      'saved_recipe_toast': '¡Receta guardada!', 'search_placeholder': 'Buscar recetas o preguntar a CHEF IA...',
      'log_out': 'Cerrar sesión',
      'new_scan': 'Nuevo escaneo', 'take_photo': 'Tomar foto', 'choose_gallery': 'Elegir de galería',
      'point_camera': 'Apunta la cámara a los ingredientes', 'ai_detect_subtitle': 'La IA detectará ingredientes y sugerirá recetas',
      'retake': 'Volver a tomar', 'gallery': 'Galería', 'retry': 'Reintentar', 'detecting_ingredients': 'Detectando ingredientes...',
      'finding_recipes': 'Recetas de distintas cocinas', 'recipes_for_ingredients': 'Recetas para tus ingredientes',
      'suggest_recipes': 'Sugeriremos 3–4 recetas con tus ingredientes', 'saved_exclamation': '¡Guardado!',
      'feedback_saved_thanks': '¡Guardado, gracias por tu opinión!',
      'review_title': 'Valorar la app', 'review_question': '¿Cómo fue tu experiencia?', 'review_subtitle': 'Tu opinión nos ayuda a mejorar Ai Chef', 'your_rating': 'TU VALORACIÓN', 'your_review': 'TU OPINIÓN', 'review_placeholder': 'Comparte tu opinión sobre Ai Chef...', 'submit_review': 'Enviar opinión', 'select_rating': 'Selecciona una valoración.',
    },
    'fr': {
      'home': 'Accueil', 'scan': 'Scanner', 'chef_ai': 'CHEF IA', 'saved': 'Sauvegardé', 'profile': 'Profil',
      'good_morning': 'Bonjour', 'good_afternoon': 'Bon après-midi', 'good_evening': 'Bonsoir',
      'what_cook': 'Que cuisinons-nous?', 'quick_actions': 'Actions rapides',
      'scan_ingredients': 'Scanner les ingrédients', 'ai_recipe_magic': 'Magie des recettes IA',
      'chat_chef': 'Chat avec CHEF IA', 'ask_anything': 'Demandez ce que vous voulez',
      'meal_planner': 'Planificateur', 'seven_day': 'Plan 7 jours',
      'shopping_list': 'Liste de courses', 'auto_generated': 'Auto-généré',
      'saved_recipes': 'Recettes sauvegardées', 'see_all': 'Voir tout',
      'analyze': 'Analyser', 'find_recipes': 'Trouver des recettes',
      'choose_cuisine': 'Choisir une cuisine 🌍', 'detected': 'Ingrédients détectés',
      'start_cooking': 'Commencer à cuisiner', 'finish_cooking': 'Terminer',
      'next_step': 'Étape suivante', 'bon_appetit': 'Bon appétit!',
      'save_recipe': 'Sauvegarder', 'cook_again': 'Cuisiner à nouveau',
      'language': 'Langue', 'appearance': 'Apparence',
      'notifications': 'Notifications', 'dietary': 'Restrictions alimentaires',
      'share': 'Partager', 'rate': 'Noter l\'app',
      'privacy': 'Politique de confidentialité', 'terms': 'Conditions d\'utilisation',
      'logout': 'Déconnexion', 'food_prefs': 'Préférences alimentaires',
      'recipes_scanned': 'Recettes scannées', 'day_streak': 'Jours consécutifs',
      'light_mode': 'Mode clair', 'dark_mode': 'Mode sombre',
      'cancel': 'Annuler', 'save': 'Enregistrer', 'edit_name': 'Modifier le nom', 'choose_avatar': 'Choisir l\'avatar',
      'your_name': 'Votre nom', 'name_updated': 'Nom mis à jour', 'log_out_confirm': 'Déconnexion?',
      'language_changed': 'Langue modifiée! Redémarrage peut être nécessaire.',
      'back_home': 'Retour à l\'accueil', 'rate_recipe': 'Noter cette recette', 'no_saved_yet': 'Aucune recette enregistrée',
      'meal_ready_subtitle': 'Votre plat est prêt! Bon appétit: %s!',
      'saved_recipe_toast': 'Recette enregistrée!', 'search_placeholder': 'Rechercher ou demander à CHEF IA...',
      'log_out': 'Déconnexion',
      'new_scan': 'Nouveau scan', 'take_photo': 'Prendre une photo', 'choose_gallery': 'Choisir dans la galerie',
      'point_camera': 'Pointez la caméra vers les ingrédients', 'ai_detect_subtitle': 'L\'IA détectera les ingrédients et proposera des recettes',
      'retake': 'Reprendre', 'gallery': 'Galerie', 'retry': 'Réessayer', 'detecting_ingredients': 'Détection des ingrédients...',
      'finding_recipes': 'Recettes de différentes cuisines', 'recipes_for_ingredients': 'Recettes pour vos ingrédients',
      'suggest_recipes': 'Nous proposerons 3–4 recettes avec vos ingrédients', 'saved_exclamation': 'Enregistré!',
      'feedback_saved_thanks': 'Enregistré, merci pour votre avis !',
      'review_title': 'Noter l\'app', 'review_question': 'Comment était votre expérience ?', 'review_subtitle': 'Votre avis nous aide à améliorer Ai Chef', 'your_rating': 'VOTRE NOTE', 'your_review': 'VOTRE AVIS', 'review_placeholder': 'Partagez votre avis sur Ai Chef...', 'submit_review': 'Envoyer l\'avis', 'select_rating': 'Veuillez choisir une note.',
    },
    'tr': {
      'home': 'Ana Sayfa', 'scan': 'Tara', 'chef_ai': 'ŞEF AI', 'saved': 'Kaydedilen', 'profile': 'Profil',
      'good_morning': 'Günaydın', 'good_afternoon': 'İyi öğleden sonralar', 'good_evening': 'İyi akşamlar',
      'what_cook': 'Ne pişirelim?', 'quick_actions': 'Hızlı İşlemler',
      'scan_ingredients': 'Malzemeleri Tara', 'ai_recipe_magic': 'AI Tarif Sihri',
      'chat_chef': 'ŞEF AI ile Sohbet', 'ask_anything': 'Her şeyi sor',
      'meal_planner': 'Yemek Planı', 'seven_day': '7 günlük plan',
      'shopping_list': 'Alışveriş Listesi', 'auto_generated': 'Otomatik',
      'saved_recipes': 'Kaydedilen Tarifler', 'see_all': 'Tümünü gör',
      'analyze': 'Analiz et', 'find_recipes': 'Tarif Bul',
      'choose_cuisine': 'Mutfak seçin 🌍', 'detected': 'Tespit edilen malzemeler',
      'start_cooking': 'Pişirmeye Başla', 'finish_cooking': 'Bitir',
      'next_step': 'Sonraki Adım', 'bon_appetit': 'Afiyet olsun!',
      'save_recipe': 'Kaydet', 'cook_again': 'Tekrar Pişir',
      'language': 'Dil', 'appearance': 'Görünüm',
      'notifications': 'Bildirimler', 'dietary': 'Diyet kısıtlamaları',
      'share': 'Paylaş', 'rate': 'Uygulamayı Oyla',
      'privacy': 'Gizlilik Politikası', 'terms': 'Kullanım Koşulları',
      'logout': 'Çıkış', 'food_prefs': 'Yemek Tercihleri',
      'recipes_scanned': 'Taranan tarifler', 'day_streak': 'Gün serisi',
      'light_mode': 'Açık mod', 'dark_mode': 'Koyu mod',
      'cancel': 'İptal', 'save': 'Kaydet', 'edit_name': 'İsim düzenle', 'choose_avatar': 'Avatar seç',
      'your_name': 'Adınız', 'name_updated': 'İsim güncellendi', 'log_out_confirm': 'Çıkış yapmak istiyor musunuz?',
      'language_changed': 'Dil değiştirildi! Yeniden başlatma gerekebilir.',
      'back_home': 'Ana sayfaya', 'rate_recipe': 'Bu tarifi değerlendir', 'no_saved_yet': 'Kayıtlı tarif yok',
      'meal_ready_subtitle': 'Yemeğiniz hazır! Afiyet olsun: %s!',
      'saved_recipe_toast': 'Tarif kaydedildi!', 'search_placeholder': 'Tarif ara veya ŞEF AI\'a sor...',
      'log_out': 'Çıkış', 'new_scan': 'Yeni tarama', 'take_photo': 'Fotoğraf çek', 'choose_gallery': 'Galeriden seç',
      'point_camera': 'Kamerayı malzemelere yönelt', 'ai_detect_subtitle': 'AI malzemeleri tespit edip tarif önerecek',
      'retake': 'Yeniden çek', 'gallery': 'Galeri', 'retry': 'Tekrar dene', 'detecting_ingredients': 'Malzemeler tespit ediliyor...',
      'finding_recipes': 'Farklı mutfaklardan tarifler bulunuyor', 'recipes_for_ingredients': 'Malzemelerinize göre tarifler',
      'suggest_recipes': 'Malzemelerinizle 3–4 tarif önereceğiz', 'saved_exclamation': 'Kaydedildi!',
      'feedback_saved_thanks': 'Kaydedildi, geri bildiriminiz için teşekkürler!',
      'review_title': 'Uygulamayı Oyla', 'review_question': 'Deneyiminiz nasıldı?', 'review_subtitle': 'Geri bildiriminiz Ai Chef\'i geliştirmemize yardımcı olur', 'your_rating': 'PUANINIZ', 'your_review': 'YORUMUNUZ', 'review_placeholder': 'Ai Chef hakkındaki düşüncelerinizi paylaşın...', 'submit_review': 'Yorumu Gönder', 'select_rating': 'Lütfen puan seçin.',
    },
    'de': {
      'home': 'Startseite', 'scan': 'Scannen', 'chef_ai': 'CHEF KI', 'saved': 'Gespeichert', 'profile': 'Profil',
      'good_morning': 'Guten Morgen', 'good_afternoon': 'Guten Tag', 'good_evening': 'Guten Abend',
      'what_cook': 'Was kochen wir?', 'quick_actions': 'Schnellaktionen',
      'scan_ingredients': 'Zutaten scannen', 'ai_recipe_magic': 'KI-Rezeptmagie',
      'chat_chef': 'Chat mit CHEF KI', 'ask_anything': 'Frag alles',
      'meal_planner': 'Mahlzeitenplaner', 'seven_day': '7-Tage-Plan',
      'shopping_list': 'Einkaufsliste', 'auto_generated': 'Automatisch',
      'saved_recipes': 'Gespeicherte Rezepte', 'see_all': 'Alle anzeigen',
      'analyze': 'Zutaten analysieren', 'find_recipes': 'Rezepte finden',
      'choose_cuisine': 'Küche wählen 🌍', 'detected': 'Erkannte Zutaten',
      'start_cooking': 'Kochen beginnen', 'finish_cooking': 'Fertig',
      'next_step': 'Nächster Schritt', 'bon_appetit': 'Guten Appetit!',
      'save_recipe': 'Speichern', 'cook_again': 'Nochmal kochen',
      'language': 'Sprache', 'appearance': 'Erscheinungsbild',
      'notifications': 'Benachrichtigungen', 'dietary': 'Ernährungseinschränkungen',
      'share': 'Teilen', 'rate': 'App bewerten',
      'privacy': 'Datenschutz', 'terms': 'Nutzungsbedingungen',
      'logout': 'Abmelden', 'food_prefs': 'Ernährungspräferenzen',
      'recipes_scanned': 'Rezepte gescannt', 'day_streak': 'Tage in Folge',
      'light_mode': 'Heller Modus', 'dark_mode': 'Dunkler Modus',
      'cancel': 'Abbrechen', 'save': 'Speichern', 'edit_name': 'Name bearbeiten', 'choose_avatar': 'Avatar wählen',
      'your_name': 'Dein Name', 'name_updated': 'Name aktualisiert', 'log_out_confirm': 'Abmelden?',
      'language_changed': 'Sprache geändert.', 'back_home': 'Zur Startseite', 'rate_recipe': 'Rezept bewerten', 'no_saved_yet': 'Keine gespeicherten Rezepte',
      'meal_ready_subtitle': 'Ihr Gericht ist fertig! Guten Appetit: %s!',
      'saved_recipe_toast': 'Rezept gespeichert!', 'search_placeholder': 'Rezepte suchen oder CHEF KI fragen...',
      'log_out': 'Abmelden', 'new_scan': 'Neuer Scan', 'take_photo': 'Foto aufnehmen', 'choose_gallery': 'Aus Galerie wählen',
      'point_camera': 'Kamera auf Zutaten richten', 'ai_detect_subtitle': 'KI erkennt Zutaten und schlägt Rezepte vor',
      'retake': 'Erneut aufnehmen', 'gallery': 'Galerie', 'retry': 'Wiederholen', 'detecting_ingredients': 'Zutaten werden erkannt...',
      'finding_recipes': 'Rezepte aus verschiedenen Küchen', 'recipes_for_ingredients': 'Rezepte für deine Zutaten',
      'suggest_recipes': 'Wir schlagen 3–4 Rezepte mit deinen Zutaten vor', 'saved_exclamation': 'Gespeichert!',
      'feedback_saved_thanks': 'Gespeichert, danke für dein Feedback!',
      'review_title': 'App bewerten', 'review_question': 'Wie war deine Erfahrung?', 'review_subtitle': 'Dein Feedback hilft uns, Ai Chef zu verbessern', 'your_rating': 'DEINE BEWERTUNG', 'your_review': 'DEINE BEWERTUNG', 'review_placeholder': 'Teile deine Gedanken zu Ai Chef...', 'submit_review': 'Bewertung senden', 'select_rating': 'Bitte Bewertung wählen.',
    },
    'it': {
      'home': 'Home', 'scan': 'Scansiona', 'chef_ai': 'CHEF IA', 'saved': 'Salvato', 'profile': 'Profilo',
      'good_morning': 'Buongiorno', 'good_afternoon': 'Buon pomeriggio', 'good_evening': 'Buonasera',
      'what_cook': 'Cosa cuciniamo?', 'quick_actions': 'Azioni rapide',
      'scan_ingredients': 'Scansiona ingredienti', 'ai_recipe_magic': 'Magia ricette IA',
      'chat_chef': 'Chat con CHEF IA', 'ask_anything': 'Chiedi tutto',
      'meal_planner': 'Pianificatore', 'seven_day': 'Piano 7 giorni',
      'shopping_list': 'Lista della spesa', 'auto_generated': 'Auto-generato',
      'saved_recipes': 'Ricette salvate', 'see_all': 'Vedi tutto',
      'analyze': 'Analizza', 'find_recipes': 'Trova ricette',
      'choose_cuisine': 'Scegli cucina 🌍', 'detected': 'Ingredienti rilevati',
      'start_cooking': 'Inizia a cucinare', 'finish_cooking': 'Finisci',
      'next_step': 'Passo successivo', 'bon_appetit': 'Buon appetito!',
      'save_recipe': 'Salva', 'cook_again': 'Cucina di nuovo',
      'language': 'Lingua', 'appearance': 'Aspetto',
      'notifications': 'Notifiche', 'dietary': 'Restrizioni dietetiche',
      'share': 'Condividi', 'rate': 'Valuta l\'app',
      'privacy': 'Privacy', 'terms': 'Termini di servizio',
      'logout': 'Esci', 'food_prefs': 'Preferenze alimentari',
      'recipes_scanned': 'Ricette scansionate', 'day_streak': 'Giorni consecutivi',
      'light_mode': 'Modalità chiara', 'dark_mode': 'Modalità scura',
      'cancel': 'Annulla', 'save': 'Salva', 'edit_name': 'Modifica nome', 'choose_avatar': 'Scegli avatar',
      'your_name': 'Il tuo nome', 'name_updated': 'Nome aggiornato', 'log_out_confirm': 'Esci?',
      'language_changed': 'Lingua modificata.', 'back_home': 'Torna alla home', 'rate_recipe': 'Valuta questa ricetta', 'no_saved_yet': 'Nessuna ricetta salvata',
      'meal_ready_subtitle': 'Il tuo piatto è pronto! Buon appetito: %s!',
      'saved_recipe_toast': 'Ricetta salvata!', 'search_placeholder': 'Cerca ricette o chiedi a CHEF IA...',
      'log_out': 'Esci', 'new_scan': 'Nuova scansione', 'take_photo': 'Scatta foto', 'choose_gallery': 'Scegli dalla galleria',
      'point_camera': 'Inquadra gli ingredienti', 'ai_detect_subtitle': 'L\'IA rileverà gli ingredienti e suggerirà ricette',
      'retake': 'Riscatta', 'gallery': 'Galleria', 'retry': 'Riprova', 'detecting_ingredients': 'Rilevamento ingredienti...',
      'finding_recipes': 'Ricette da diverse cucine', 'recipes_for_ingredients': 'Ricette per i tuoi ingredienti',
      'suggest_recipes': 'Suggeriremo 3–4 ricette con i tuoi ingredienti', 'saved_exclamation': 'Salvato!',
      'feedback_saved_thanks': 'Salvato, grazie per il tuo feedback!',
      'review_title': 'Valuta l\'app', 'review_question': 'Com\'è stata la tua esperienza?', 'review_subtitle': 'Il tuo feedback ci aiuta a migliorare Ai Chef', 'your_rating': 'LA TUA VALUTAZIONE', 'your_review': 'LA TUA RECENSIONE', 'review_placeholder': 'Condividi le tue opinioni su Ai Chef...', 'submit_review': 'Invia recensione', 'select_rating': 'Seleziona una valutazione.',
    },
    'pt': {
      'home': 'Início', 'scan': 'Escanear', 'chef_ai': 'CHEF IA', 'saved': 'Salvo', 'profile': 'Perfil',
      'good_morning': 'Bom dia', 'good_afternoon': 'Boa tarde', 'good_evening': 'Boa noite',
      'what_cook': 'O que vamos cozinhar?', 'quick_actions': 'Ações rápidas',
      'scan_ingredients': 'Escanear ingredientes', 'ai_recipe_magic': 'Magia de receitas IA',
      'chat_chef': 'Chat com CHEF IA', 'ask_anything': 'Pergunte qualquer coisa',
      'meal_planner': 'Planejador', 'seven_day': 'Plano 7 dias',
      'shopping_list': 'Lista de compras', 'auto_generated': 'Auto-gerado',
      'saved_recipes': 'Receitas salvas', 'see_all': 'Ver tudo',
      'analyze': 'Analisar', 'find_recipes': 'Encontrar receitas',
      'choose_cuisine': 'Escolha culinária 🌍', 'detected': 'Ingredientes detectados',
      'start_cooking': 'Começar a cozinhar', 'finish_cooking': 'Terminar',
      'next_step': 'Próximo passo', 'bon_appetit': 'Bom apetite!',
      'save_recipe': 'Salvar', 'cook_again': 'Cozinhar novamente',
      'language': 'Idioma', 'appearance': 'Aparência',
      'notifications': 'Notificações', 'dietary': 'Restrições dietéticas',
      'share': 'Compartilhar', 'rate': 'Avaliar app',
      'privacy': 'Privacidade', 'terms': 'Termos de serviço',
      'logout': 'Sair', 'food_prefs': 'Preferências alimentares',
      'recipes_scanned': 'Receitas escaneadas', 'day_streak': 'Dias seguidos',
      'light_mode': 'Modo claro', 'dark_mode': 'Modo escuro',
      'cancel': 'Cancelar', 'save': 'Salvar', 'edit_name': 'Editar nome', 'choose_avatar': 'Escolher avatar',
      'your_name': 'Seu nome', 'name_updated': 'Nome atualizado', 'log_out_confirm': 'Sair?',
      'language_changed': 'Idioma alterado.', 'back_home': 'Voltar ao início', 'rate_recipe': 'Avaliar esta receita', 'no_saved_yet': 'Nenhuma receita salva',
      'meal_ready_subtitle': 'Sua refeição está pronta! Bom apetite: %s!',
      'saved_recipe_toast': 'Receita salva!', 'search_placeholder': 'Buscar receitas ou perguntar ao CHEF IA...',
      'log_out': 'Sair', 'new_scan': 'Nova varredura', 'take_photo': 'Tirar foto', 'choose_gallery': 'Escolher da galeria',
      'point_camera': 'Aponte a câmera para os ingredientes', 'ai_detect_subtitle': 'A IA detectará ingredientes e sugerirá receitas',
      'retake': 'Tirar novamente', 'gallery': 'Galeria', 'retry': 'Tentar novamente', 'detecting_ingredients': 'Detectando ingredientes...',
      'finding_recipes': 'Receitas de diferentes culinárias', 'recipes_for_ingredients': 'Receitas para seus ingredientes',
      'suggest_recipes': 'Sugeriremos 3–4 receitas com seus ingredientes', 'saved_exclamation': 'Salvo!',
      'feedback_saved_thanks': 'Salvo, obrigado pelo seu feedback!',
      'review_title': 'Avaliar app', 'review_question': 'Como foi sua experiência?', 'review_subtitle': 'Seu feedback nos ajuda a melhorar o Ai Chef', 'your_rating': 'SUA AVALIAÇÃO', 'your_review': 'SUA OPINIÃO', 'review_placeholder': 'Compartilhe seus pensamentos sobre o Ai Chef...', 'submit_review': 'Enviar opinião', 'select_rating': 'Selecione uma avaliação.',
    },
    'ar': {
      'home': 'الرئيسية', 'scan': 'مسح', 'chef_ai': 'شيف AI', 'saved': 'محفوظ', 'profile': 'الملف',
      'good_morning': 'صباح الخير', 'good_afternoon': 'مساء الخير', 'good_evening': 'مساء النور',
      'what_cook': 'ماذا نطبخ؟', 'quick_actions': 'إجراءات سريعة',
      'scan_ingredients': 'مسح المكونات', 'ai_recipe_magic': 'سحر وصفات AI',
      'chat_chef': 'دردشة مع شيف AI', 'ask_anything': 'اسأل أي شيء',
      'meal_planner': 'مخطط الوجبات', 'seven_day': 'خطة 7 أيام',
      'shopping_list': 'قائمة التسوق', 'auto_generated': 'تلقائي',
      'saved_recipes': 'الوصفات المحفوظة', 'see_all': 'عرض الكل',
      'analyze': 'تحليل', 'find_recipes': 'إيجاد وصفات',
      'choose_cuisine': 'اختر مطبخاً 🌍', 'detected': 'المكونات المكتشفة',
      'start_cooking': 'ابدأ الطبخ', 'finish_cooking': 'انتهى',
      'next_step': 'الخطوة التالية', 'bon_appetit': 'بالهناء والشفاء!',
      'save_recipe': 'حفظ', 'cook_again': 'اطبخ مرة أخرى',
      'language': 'اللغة', 'appearance': 'المظهر',
      'notifications': 'الإشعارات', 'dietary': 'القيود الغذائية',
      'share': 'مشاركة', 'rate': 'قيّم التطبيق',
      'privacy': 'الخصوصية', 'terms': 'شروط الخدمة',
      'logout': 'تسجيل الخروج', 'food_prefs': 'تفضيلات الطعام',
      'recipes_scanned': 'الوصفات الممسوحة', 'day_streak': 'أيام متتالية',
      'light_mode': 'الوضع الفاتح', 'dark_mode': 'الوضع الداكن',
      'cancel': 'إلغاء', 'save': 'حفظ', 'edit_name': 'تعديل الاسم', 'choose_avatar': 'اختر الصورة الرمزية',
      'your_name': 'اسمك', 'name_updated': 'تم تحديث الاسم', 'log_out_confirm': 'تسجيل الخروج؟',
      'language_changed': 'تم تغيير اللغة.', 'back_home': 'العودة للرئيسية', 'rate_recipe': 'قيّم الوصفة', 'no_saved_yet': 'لا توجد وصفات محفوظة',
      'meal_ready_subtitle': 'وجبتك جاهزة! بالهناء والشفاء: %s!',
      'saved_recipe_toast': 'تم حفظ الوصفة!', 'search_placeholder': 'ابحث عن وصفات أو اسأل شيف AI...',
      'log_out': 'تسجيل الخروج', 'new_scan': 'مسح جديد', 'take_photo': 'التقط صورة', 'choose_gallery': 'اختر من المعرض',
      'point_camera': 'وجّه الكاميرا للمكونات', 'ai_detect_subtitle': 'ستكتشف AI المكونات وتقترح وصفات',
      'retake': 'إعادة المحاولة', 'gallery': 'المعرض', 'retry': 'إعادة', 'detecting_ingredients': 'جاري اكتشاف المكونات...',
      'finding_recipes': 'وصفات من مطابخ مختلفة', 'recipes_for_ingredients': 'وصفات لمكوناتك',
      'suggest_recipes': 'سنقترح 3–4 وصفات باستخدام مكوناتك', 'saved_exclamation': 'تم الحفظ!',
      'feedback_saved_thanks': 'تم الحفظ، شكراً على ملاحظاتك!',
      'review_title': 'قيّم التطبيق', 'review_question': 'كيف كانت تجربتك؟', 'review_subtitle': 'ملاحظاتك تساعدنا على تحسين Ai Chef', 'your_rating': 'تقييمك', 'your_review': 'مراجعتك', 'review_placeholder': 'شارك أفكارك حول Ai Chef...', 'submit_review': 'إرسال المراجعة', 'select_rating': 'يرجى اختيار التقييم.',
    },
    'zh': {
      'home': '首页', 'scan': '扫描', 'chef_ai': 'AI厨师', 'saved': '已保存', 'profile': '个人资料',
      'good_morning': '早上好', 'good_afternoon': '下午好', 'good_evening': '晚上好',
      'what_cook': '我们做什么？', 'quick_actions': '快速操作',
      'scan_ingredients': '扫描食材', 'ai_recipe_magic': 'AI食谱魔法',
      'chat_chef': '与AI厨师聊天', 'ask_anything': '问任何事',
      'meal_planner': '饮食计划', 'seven_day': '7天计划',
      'shopping_list': '购物清单', 'auto_generated': '自动生成',
      'saved_recipes': '已保存食谱', 'see_all': '查看全部',
      'analyze': '分析', 'find_recipes': '查找食谱',
      'choose_cuisine': '选择菜系 🌍', 'detected': '检测到的食材',
      'start_cooking': '开始烹饪', 'finish_cooking': '完成',
      'next_step': '下一步', 'bon_appetit': '用餐愉快！',
      'save_recipe': '保存', 'cook_again': '再次烹饪',
      'language': '语言', 'appearance': '外观',
      'notifications': '通知', 'dietary': '饮食限制',
      'share': '分享', 'rate': '评价应用',
      'privacy': '隐私政策', 'terms': '服务条款',
      'logout': '退出', 'food_prefs': '饮食偏好',
      'recipes_scanned': '已扫描食谱', 'day_streak': '连续天数',
      'light_mode': '浅色模式', 'dark_mode': '深色模式',
      'cancel': '取消', 'save': '保存', 'edit_name': '编辑姓名', 'choose_avatar': '选择头像',
      'your_name': '您的姓名', 'name_updated': '姓名已更新', 'log_out_confirm': '确定退出？',
      'language_changed': '语言已更改.', 'back_home': '返回首页', 'rate_recipe': '评价此食谱', 'no_saved_yet': '暂无保存的食谱',
      'meal_ready_subtitle': '您的美食准备好了！请享用您美味的%s！',
      'saved_recipe_toast': '食谱已保存！', 'search_placeholder': '搜索食谱或询问AI厨师...',
      'log_out': '退出', 'new_scan': '新扫描', 'take_photo': '拍照', 'choose_gallery': '从相册选择',
      'point_camera': '将相机对准食材', 'ai_detect_subtitle': 'AI将检测食材并推荐食谱',
      'retake': '重拍', 'gallery': '相册', 'retry': '重试', 'detecting_ingredients': '正在检测食材...',
      'finding_recipes': '来自不同菜系的食谱', 'recipes_for_ingredients': '根据您的食材的食谱',
      'suggest_recipes': '我们将根据您的食材推荐3–4道食谱', 'saved_exclamation': '已保存！',
      'feedback_saved_thanks': '已保存，感谢您的反馈！',
      'review_title': '评价应用', 'review_question': '您的体验如何？', 'review_subtitle': '您的反馈帮助我们改进 Ai Chef', 'your_rating': '您的评分', 'your_review': '您的评价', 'review_placeholder': '分享您对 Ai Chef 的看法...', 'submit_review': '提交评价', 'select_rating': '请选择评分。',
    },
    'ja': {
      'home': 'ホーム', 'scan': 'スキャン', 'chef_ai': 'シェフAI', 'saved': '保存済み', 'profile': 'プロフィール',
      'good_morning': 'おはようございます', 'good_afternoon': 'こんにちは', 'good_evening': 'こんばんは',
      'what_cook': '何を作りますか？', 'quick_actions': 'クイックアクション',
      'scan_ingredients': '食材をスキャン', 'ai_recipe_magic': 'AIレシピマジック',
      'chat_chef': 'シェフAIとチャット', 'ask_anything': '何でも聞いて',
      'meal_planner': '食事プランナー', 'seven_day': '7日間プラン',
      'shopping_list': 'ショッピングリスト', 'auto_generated': '自動生成',
      'saved_recipes': '保存済みレシピ', 'see_all': 'すべて見る',
      'analyze': '分析', 'find_recipes': 'レシピを探す',
      'choose_cuisine': '料理を選択 🌍', 'detected': '検出された食材',
      'start_cooking': '調理開始', 'finish_cooking': '完了',
      'next_step': '次のステップ', 'bon_appetit': 'いただきます！',
      'save_recipe': '保存', 'cook_again': 'もう一度調理',
      'language': '言語', 'appearance': '外観',
      'notifications': '通知', 'dietary': '食事制限',
      'share': '共有', 'rate': 'アプリを評価',
      'privacy': 'プライバシー', 'terms': '利用規約',
      'logout': 'ログアウト', 'food_prefs': '食の好み',
      'recipes_scanned': 'スキャンしたレシピ', 'day_streak': '連続日数',
      'light_mode': 'ライトモード', 'dark_mode': 'ダークモード',
      'cancel': 'キャンセル', 'save': '保存', 'edit_name': '名前を編集', 'choose_avatar': 'アバターを選択',
      'your_name': 'あなたの名前', 'name_updated': '名前を更新しました', 'log_out_confirm': 'ログアウトしますか？',
      'language_changed': '言語を変更しました.', 'back_home': 'ホームに戻る', 'rate_recipe': 'このレシピを評価', 'no_saved_yet': '保存されたレシピはありません',
      'meal_ready_subtitle': '料理ができました！おいしい%sをお楽しみください！',
      'saved_recipe_toast': 'レシピを保存しました！', 'search_placeholder': 'レシピを検索またはシェフAIに質問...',
      'log_out': 'ログアウト', 'new_scan': '新規スキャン', 'take_photo': '写真を撮る', 'choose_gallery': 'ギャラリーから選択',
      'point_camera': 'カメラを食材に向けて', 'ai_detect_subtitle': 'AIが食材を検出してレシピを提案します',
      'retake': '再撮影', 'gallery': 'ギャラリー', 'retry': '再試行', 'detecting_ingredients': '食材を検出しています...',
      'finding_recipes': 'さまざまな料理のレシピ', 'recipes_for_ingredients': 'あなたの食材に合うレシピ',
      'suggest_recipes': '食材に合ったレシピを3〜4品提案します', 'saved_exclamation': '保存しました！',
      'feedback_saved_thanks': '保存しました。フィードバックありがとうございます！',
      'review_title': 'アプリを評価', 'review_question': '体験はいかがでしたか？', 'review_subtitle': 'フィードバックでAi Chefを改善します', 'your_rating': '評価', 'your_review': 'レビュー', 'review_placeholder': 'Ai Chefについての感想を共有...', 'submit_review': 'レビューを送信', 'select_rating': '評価を選択してください。',
    },
    'ko': {
      'home': '홈', 'scan': '스캔', 'chef_ai': '셰프 AI', 'saved': '저장됨', 'profile': '프로필',
      'good_morning': '좋은 아침', 'good_afternoon': '안녕하세요', 'good_evening': '좋은 저녁',
      'what_cook': '무엇을 요리할까요?', 'quick_actions': '빠른 작업',
      'scan_ingredients': '재료 스캔', 'ai_recipe_magic': 'AI 레시피 마법',
      'chat_chef': '셰프 AI와 채팅', 'ask_anything': '무엇이든 물어보세요',
      'meal_planner': '식사 계획', 'seven_day': '7일 계획',
      'shopping_list': '쇼핑 목록', 'auto_generated': '자동 생성',
      'saved_recipes': '저장된 레시피', 'see_all': '모두 보기',
      'analyze': '분석', 'find_recipes': '레시피 찾기',
      'choose_cuisine': '요리 선택 🌍', 'detected': '감지된 재료',
      'start_cooking': '요리 시작', 'finish_cooking': '완료',
      'next_step': '다음 단계', 'bon_appetit': '맛있게 드세요!',
      'save_recipe': '저장', 'cook_again': '다시 요리',
      'language': '언어', 'appearance': '외관',
      'notifications': '알림', 'dietary': '식이 제한',
      'share': '공유', 'rate': '앱 평가',
      'privacy': '개인정보', 'terms': '이용약관',
      'logout': '로그아웃', 'food_prefs': '음식 선호도',
      'recipes_scanned': '스캔한 레시피', 'day_streak': '연속 일수',
      'light_mode': '라이트 모드', 'dark_mode': '다크 모드',
      'cancel': '취소', 'save': '저장', 'edit_name': '이름 편집', 'choose_avatar': '아바타 선택',
      'your_name': '이름', 'name_updated': '이름이 업데이트되었습니다', 'log_out_confirm': '로그아웃하시겠습니까?',
      'language_changed': '언어가 변경되었습니다.', 'back_home': '홈으로', 'rate_recipe': '이 레시피 평가', 'no_saved_yet': '저장된 레시피 없음',
      'meal_ready_subtitle': '요리가 완성되었습니다! 맛있는 %s 맛있게 드세요!',
      'saved_recipe_toast': '레시피가 저장되었습니다!', 'search_placeholder': '레시피 검색 또는 셰프 AI에게 질문...',
      'log_out': '로그아웃', 'new_scan': '새 스캔', 'take_photo': '사진 촬영', 'choose_gallery': '갤러리에서 선택',
      'point_camera': '카메라를 재료에 맞추세요', 'ai_detect_subtitle': 'AI가 재료를 감지하고 레시피를 추천합니다',
      'retake': '다시 촬영', 'gallery': '갤러리', 'retry': '재시도', 'detecting_ingredients': '재료 감지 중...',
      'finding_recipes': '다양한 요리의 레시피', 'recipes_for_ingredients': '재료에 맞는 레시피',
      'suggest_recipes': '재료로 3–4가지 레시피를 추천합니다', 'saved_exclamation': '저장됨!',
      'feedback_saved_thanks': '저장되었습니다. 피드백 감사합니다!',
      'review_title': '앱 평가', 'review_question': '경험은 어떠셨나요?', 'review_subtitle': '피드백이 Ai Chef 개선에 도움이 됩니다', 'your_rating': '평가', 'your_review': '리뷰', 'review_placeholder': 'Ai Chef에 대한 생각을 공유해 주세요...', 'submit_review': '리뷰 제출', 'select_rating': '평가를 선택하세요.',
    },
    'hi': {
      'home': 'होम', 'scan': 'स्कैन', 'chef_ai': 'शेफ AI', 'saved': 'सहेजा', 'profile': 'प्रोफाइल',
      'good_morning': 'सुप्रभात', 'good_afternoon': 'नमस्ते', 'good_evening': 'शुभ संध्या',
      'what_cook': 'क्या पकाएं?', 'quick_actions': 'त्वरित क्रियाएं',
      'scan_ingredients': 'सामग्री स्कैन करें', 'ai_recipe_magic': 'AI रेसिपी जादू',
      'chat_chef': 'शेफ AI से चैट', 'ask_anything': 'कुछ भी पूछें',
      'meal_planner': 'भोजन योजना', 'seven_day': '7 दिन की योजना',
      'shopping_list': 'खरीदारी सूची', 'auto_generated': 'स्वतः निर्मित',
      'saved_recipes': 'सहेजी रेसिपी', 'see_all': 'सभी देखें',
      'analyze': 'विश्लेषण', 'find_recipes': 'रेसिपी खोजें',
      'choose_cuisine': 'व्यंजन चुनें 🌍', 'detected': 'पहचानी सामग्री',
      'start_cooking': 'पकाना शुरू करें', 'finish_cooking': 'समाप्त',
      'next_step': 'अगला कदम', 'bon_appetit': 'भोजन का आनंद लें!',
      'save_recipe': 'सहेजें', 'cook_again': 'फिर से पकाएं',
      'language': 'भाषा', 'appearance': 'दिखावट',
      'notifications': 'सूचनाएं', 'dietary': 'आहार प्रतिबंध',
      'share': 'साझा करें', 'rate': 'ऐप रेट करें',
      'privacy': 'गोपनीयता', 'terms': 'सेवा की शर्तें',
      'logout': 'लॉग आउट', 'food_prefs': 'खाद्य प्राथमिकताएं',
      'recipes_scanned': 'स्कैन की रेसिपी', 'day_streak': 'लगातार दिन',
      'light_mode': 'लाइट मोड', 'dark_mode': 'डार्क मोड',
      'cancel': 'रद्द करें', 'save': 'सहेजें', 'edit_name': 'नाम संपादित करें', 'choose_avatar': 'अवतार चुनें',
      'your_name': 'आपका नाम', 'name_updated': 'नाम अपडेट हो गया', 'log_out_confirm': 'लॉग आउट करें?',
      'language_changed': 'भाषा बदल गई.', 'back_home': 'होम पर वापस', 'rate_recipe': 'इस रेसिपी को रेट करें', 'no_saved_yet': 'कोई सहेजी रेसिपी नहीं',
      'meal_ready_subtitle': 'आपका भोजन तैयार है! अपने स्वादिष्ट %s का आनंद लें!',
      'saved_recipe_toast': 'रेसिपी सहेजी गई!', 'search_placeholder': 'रेसिपी खोजें या शेफ AI से पूछें...',
      'log_out': 'लॉग आउट', 'new_scan': 'नया स्कैन', 'take_photo': 'फोटो लें', 'choose_gallery': 'गैलरी से चुनें',
      'point_camera': 'कैमरा सामग्री की ओर करें', 'ai_detect_subtitle': 'AI सामग्री का पता लगाएगा और रेसिपी सुझाएगा',
      'retake': 'दोबारा लें', 'gallery': 'गैलरी', 'retry': 'पुनः प्रयास', 'detecting_ingredients': 'सामग्री का पता लगाया जा रहा है...',
      'finding_recipes': 'विभिन्न व्यंजनों की रेसिपी', 'recipes_for_ingredients': 'आपकी सामग्री के लिए रेसिपी',
      'suggest_recipes': 'आपकी सामग्री से 3–4 रेसिपी सुझाएंगे', 'saved_exclamation': 'सहेजा गया!',
      'feedback_saved_thanks': 'सहेजा गया, आपकी प्रतिक्रिया के लिए धन्यवाद!',
      'review_title': 'ऐप रेट करें', 'review_question': 'आपका अनुभव कैसा रहा?', 'review_subtitle': 'आपकी प्रतिक्रिया Ai Chef को बेहतर बनाने में मदद करती है', 'your_rating': 'आपकी रेटिंग', 'your_review': 'आपकी समीक्षा', 'review_placeholder': 'Ai Chef के बारे में अपने विचार साझा करें...', 'submit_review': 'समीक्षा जमा करें', 'select_rating': 'कृपया रेटिंग चुनें।',
    },
    'id': {
      'home': 'Beranda', 'scan': 'Pindai', 'chef_ai': 'CHEF AI', 'saved': 'Tersimpan', 'profile': 'Profil',
      'good_morning': 'Selamat pagi', 'good_afternoon': 'Selamat siang', 'good_evening': 'Selamat malam',
      'what_cook': 'Apa yang kita masak?', 'quick_actions': 'Tindakan cepat',
      'scan_ingredients': 'Pindai bahan', 'ai_recipe_magic': 'Sihir resep AI',
      'chat_chef': 'Chat dengan CHEF AI', 'ask_anything': 'Tanya apa saja',
      'meal_planner': 'Perencana makan', 'seven_day': 'Rencana 7 hari',
      'shopping_list': 'Daftar belanja', 'auto_generated': 'Otomatis',
      'saved_recipes': 'Resep tersimpan', 'see_all': 'Lihat semua',
      'analyze': 'Analisis', 'find_recipes': 'Cari resep',
      'choose_cuisine': 'Pilih masakan 🌍', 'detected': 'Bahan terdeteksi',
      'start_cooking': 'Mulai memasak', 'finish_cooking': 'Selesai',
      'next_step': 'Langkah berikutnya', 'bon_appetit': 'Selamat makan!',
      'save_recipe': 'Simpan', 'cook_again': 'Masak lagi',
      'language': 'Bahasa', 'appearance': 'Tampilan',
      'notifications': 'Notifikasi', 'dietary': 'Batasan diet',
      'share': 'Bagikan', 'rate': 'Nilai aplikasi',
      'privacy': 'Privasi', 'terms': 'Ketentuan layanan',
      'logout': 'Keluar', 'food_prefs': 'Preferensi makanan',
      'recipes_scanned': 'Resep dipindai', 'day_streak': 'Hari berturut-turut',
      'light_mode': 'Mode terang', 'dark_mode': 'Mode gelap',
      'cancel': 'Batal', 'save': 'Simpan', 'edit_name': 'Edit nama', 'choose_avatar': 'Pilih avatar',
      'your_name': 'Nama Anda', 'name_updated': 'Nama diperbarui', 'log_out_confirm': 'Keluar?',
      'language_changed': 'Bahasa diubah.', 'back_home': 'Kembali ke beranda', 'rate_recipe': 'Nilai resep ini', 'no_saved_yet': 'Belum ada resep tersimpan',
      'meal_ready_subtitle': 'Hidangan Anda siap! Selamat menikmati %s yang lezat!',
      'saved_recipe_toast': 'Resep disimpan!', 'search_placeholder': 'Cari resep atau tanya CHEF AI...',
      'log_out': 'Keluar', 'new_scan': 'Pindai baru', 'take_photo': 'Ambil foto', 'choose_gallery': 'Pilih dari galeri',
      'point_camera': 'Arahkan kamera ke bahan', 'ai_detect_subtitle': 'AI akan mendeteksi bahan dan menyarankan resep',
      'retake': 'Ambil ulang', 'gallery': 'Galeri', 'retry': 'Coba lagi', 'detecting_ingredients': 'Mendeteksi bahan...',
      'finding_recipes': 'Resep dari berbagai masakan', 'recipes_for_ingredients': 'Resep untuk bahan Anda',
      'suggest_recipes': 'Kami akan menyarankan 3–4 resep dengan bahan Anda', 'saved_exclamation': 'Tersimpan!',
      'feedback_saved_thanks': 'Tersimpan, terima kasih atas masukan Anda!',
      'review_title': 'Nilai aplikasi', 'review_question': 'Bagaimana pengalaman Anda?', 'review_subtitle': 'Masukan Anda membantu kami meningkatkan Ai Chef', 'your_rating': 'NILAI ANDA', 'your_review': 'ULASAN ANDA', 'review_placeholder': 'Bagikan pemikiran Anda tentang Ai Chef...', 'submit_review': 'Kirim ulasan', 'select_rating': 'Pilih nilai.',
    },
    'nl': {
      'home': 'Home', 'scan': 'Scannen', 'chef_ai': 'CHEF AI', 'saved': 'Opgeslagen', 'profile': 'Profiel',
      'good_morning': 'Goedemorgen', 'good_afternoon': 'Goedemiddag', 'good_evening': 'Goedenavond',
      'what_cook': 'Wat koken we?', 'quick_actions': 'Snelle acties',
      'scan_ingredients': 'Ingrediënten scannen', 'ai_recipe_magic': 'AI-receptmagie',
      'chat_chef': 'Chat met CHEF AI', 'ask_anything': 'Vraag alles',
      'meal_planner': 'Maaltijdplanner', 'seven_day': '7-daags plan',
      'shopping_list': 'Boodschappenlijst', 'auto_generated': 'Automatisch',
      'saved_recipes': 'Opgeslagen recepten', 'see_all': 'Alles zien',
      'analyze': 'Analyseren', 'find_recipes': 'Recepten vinden',
      'choose_cuisine': 'Keuken kiezen 🌍', 'detected': 'Gedetecteerde ingrediënten',
      'start_cooking': 'Begin met koken', 'finish_cooking': 'Klaar',
      'next_step': 'Volgende stap', 'bon_appetit': 'Eet smakelijk!',
      'save_recipe': 'Opslaan', 'cook_again': 'Opnieuw koken',
      'language': 'Taal', 'appearance': 'Uiterlijk',
      'notifications': 'Meldingen', 'dietary': 'Dieetbeperkingen',
      'share': 'Delen', 'rate': 'App beoordelen',
      'privacy': 'Privacy', 'terms': 'Servicevoorwaarden',
      'logout': 'Uitloggen', 'food_prefs': 'Voedselvoorkeuren',
      'recipes_scanned': 'Gescande recepten', 'day_streak': 'Dagen op rij',
      'light_mode': 'Lichte modus', 'dark_mode': 'Donkere modus',
      'cancel': 'Annuleren', 'save': 'Opslaan', 'edit_name': 'Naam bewerken', 'choose_avatar': 'Avatar kiezen',
      'your_name': 'Je naam', 'name_updated': 'Naam bijgewerkt', 'log_out_confirm': 'Uitloggen?',
      'language_changed': 'Taal gewijzigd.', 'back_home': 'Terug naar home', 'rate_recipe': 'Beoordeel dit recept', 'no_saved_yet': 'Geen opgeslagen recepten',
      'meal_ready_subtitle': 'Je maaltijd is klaar! Geniet van je heerlijke %s!',
      'saved_recipe_toast': 'Recept opgeslagen!', 'search_placeholder': 'Zoek recepten of vraag CHEF AI...',
      'log_out': 'Uitloggen', 'new_scan': 'Nieuwe scan', 'take_photo': 'Foto maken', 'choose_gallery': 'Kies uit galerij',
      'point_camera': 'Richt camera op ingrediënten', 'ai_detect_subtitle': 'AI detecteert ingrediënten en stelt recepten voor',
      'retake': 'Opnieuw nemen', 'gallery': 'Galerij', 'retry': 'Opnieuw', 'detecting_ingredients': 'Ingrediënten detecteren...',
      'finding_recipes': 'Recepten uit verschillende keukens', 'recipes_for_ingredients': 'Recepten voor je ingrediënten',
      'suggest_recipes': 'We stellen 3–4 recepten voor met je ingrediënten', 'saved_exclamation': 'Opgeslagen!',
      'feedback_saved_thanks': 'Opgeslagen, bedankt voor je feedback!',
      'review_title': 'App beoordelen', 'review_question': 'Hoe was je ervaring?', 'review_subtitle': 'Je feedback helpt ons Ai Chef te verbeteren', 'your_rating': 'JOUW BEOORDELING', 'your_review': 'JOUW BEOORDELING', 'review_placeholder': 'Deel je gedachten over Ai Chef...', 'submit_review': 'Beoordeling verzenden', 'select_rating': 'Selecteer een beoordeling.',
    },
  };
}
